# Service configuration
server:
  port: 21090
  servlet:
    context-path: /api/personal-heath/v1.0
# API address prefix, which is used for interface interception and permit
my-server:
  api-context-path: /api/personal-heath/v1.0
#MySQL and file upload limit configuration
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/personal_health?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: Wrx050812@
# Have Mybatis find the XML mapping file in the Mapper directory
mybatis:
  mapper-locations: classpath:mapper/*.xml




